# -*- coding: utf-8 -*-
"""NLP_intro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FjKI4m28qsTlyO8mlEsiJCuxOcxa6V0a
"""

from bs4 import BeautifulSoup
import requests
#to seperate normal and words for sentiments
import nltk
nltk.download('stopwords')

#stopwords.words('english')
#accessing web url
web_data=requests.get('https://en.wikipedia.org/wiki/Ghost')
web_data#response code of http protocol
#200-means url is ok
#302-means url is redirected
#404-means url not found
#505-means server not permitting for web scrapping

#now get actual data of any website /url
html_data=web_data.text
#html_data

#parsing            html data , parser 
soup=BeautifulSoup(html_data,'lxml')
type(soup)

#finding all data
clean_data=soup.get_text()
#print(clean_data)

#saving data permanently
with open('mywebdata.txt','w+') as f:
  f.write(clean_data)

#read from a file
f=open('mywebdata.txt','r')
mydata=f.read()
f.close()

type(mydata)

#split
import time
new_data1=[i for i in mydata.split()] #split all string data by \n

#NLTK graphs
import matplotlib.pyplot as plt
#-- %matplotlib inline #in case matplotlib not supporting by default with pandas or nltk
#to replace plt.show() from any platform

[i for i in dir(nltk) if 'Freq' in i]

nlp_data=nltk.FreqDist(new_data1)

nlp_data.plot(20)

#we can remove stop words from newdata1 then plot the graph
from nltk.corpus import stopwords
#removing stopwords 
removed_data=[i for i in new_data1 if i not in stopwords.words('english')]

#applying NLTK FreqDist
nlpremove=nltk.FreqDist(removed_data)

nlpremove.plot(20)

